'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SaldosServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConsultaSueldo", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ConsultaSueldo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private S_PrimaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private S_SubsidioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private S_SueldoField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property S_Prima() As String
            Get
                Return Me.S_PrimaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.S_PrimaField, value) <> true) Then
                    Me.S_PrimaField = value
                    Me.RaisePropertyChanged("S_Prima")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property S_Subsidio() As String
            Get
                Return Me.S_SubsidioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.S_SubsidioField, value) <> true) Then
                    Me.S_SubsidioField = value
                    Me.RaisePropertyChanged("S_Subsidio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property S_Sueldo() As Double
            Get
                Return Me.S_SueldoField
            End Get
            Set
                If (Me.S_SueldoField.Equals(value) <> true) Then
                    Me.S_SueldoField = value
                    Me.RaisePropertyChanged("S_Sueldo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="SaldosServiceReference.SueldosIService")>  _
    Public Interface SueldosIService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SueldosIService/BuscarSueldo", ReplyAction:="http://tempuri.org/SueldosIService/BuscarSueldoResponse")>  _
        Function BuscarSueldo(ByVal sueldo As Double) As SaldosServiceReference.ConsultaSueldo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SueldosIService/BuscarSueldo", ReplyAction:="http://tempuri.org/SueldosIService/BuscarSueldoResponse")>  _
        Function BuscarSueldoAsync(ByVal sueldo As Double) As System.Threading.Tasks.Task(Of SaldosServiceReference.ConsultaSueldo)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SueldosIServiceChannel
        Inherits SaldosServiceReference.SueldosIService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SueldosIServiceClient
        Inherits System.ServiceModel.ClientBase(Of SaldosServiceReference.SueldosIService)
        Implements SaldosServiceReference.SueldosIService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function BuscarSueldo(ByVal sueldo As Double) As SaldosServiceReference.ConsultaSueldo Implements SaldosServiceReference.SueldosIService.BuscarSueldo
            Return MyBase.Channel.BuscarSueldo(sueldo)
        End Function
        
        Public Function BuscarSueldoAsync(ByVal sueldo As Double) As System.Threading.Tasks.Task(Of SaldosServiceReference.ConsultaSueldo) Implements SaldosServiceReference.SueldosIService.BuscarSueldoAsync
            Return MyBase.Channel.BuscarSueldoAsync(sueldo)
        End Function
    End Class
End Namespace
